-- CREACIÓN DE BASE DE DATOS
DROP DATABASE IF EXISTS libreriasalas;
CREATE DATABASE libreriasalas;
USE libreriasalas;

-- TABLA CLIENTE
CREATE TABLE cliente (
  ID_Cliente VARCHAR(15) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Direccion VARCHAR(50) NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA EDITORIAL
CREATE TABLE editorial (
  ID_Editorial VARCHAR(30) NOT NULL,
  Nombre VARCHAR(30) NOT NULL,
  Direccion VARCHAR(50) NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Pais VARCHAR(30) NOT NULL,
  Catalogo TEXT NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Editorial)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA EMPLEADO
CREATE TABLE empleado (
  ID_Empleado VARCHAR(15) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Puesto VARCHAR(30) NOT NULL,
  Direccion VARCHAR(50) NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Empleado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA USUARIOS
CREATE TABLE usuarios (
  ID_Usuario VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Contraseña VARCHAR(20) NOT NULL,
  Rol VARCHAR(30) NOT NULL,
  ID_Empleado VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID_Usuario),
  KEY (ID_Empleado),
  CONSTRAINT usuarios_ibfk_1 FOREIGN KEY (ID_Empleado) REFERENCES empleado (ID_Empleado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA LIBRO
CREATE TABLE libro (
  ISBN VARCHAR(13) NOT NULL,
  Titulo VARCHAR(50) NOT NULL,
  Categoria VARCHAR(30) NOT NULL,
  Autor VARCHAR(50) NOT NULL,
  ID_Editorial VARCHAR(30) NOT NULL,
  Precio INT(5) NOT NULL,
  Stock INT(5) NOT NULL,
  PRIMARY KEY (ISBN),
  KEY (ID_Editorial),
  CONSTRAINT libro_ibfk_1 FOREIGN KEY (ID_Editorial) REFERENCES editorial (ID_Editorial)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA INVENTARIO
CREATE TABLE inventario (
  ID_Inventario VARCHAR(15) NOT NULL,
  Fecha_Actu DATE NOT NULL,
  ISBN VARCHAR(13) NOT NULL,
  PRIMARY KEY (ID_Inventario),
  KEY (ISBN),
  CONSTRAINT inventario_ibfk_1 FOREIGN KEY (ISBN) REFERENCES libro (ISBN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA VENTA (SIN FECHA)
CREATE TABLE venta (
  ID_Venta VARCHAR(15) NOT NULL,
  Monto_Total INT(5) NOT NULL,
  ID_Cliente VARCHAR(15) NOT NULL,
  ID_Empleado VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID_Venta),
  KEY (ID_Cliente),
  KEY (ID_Empleado),
  CONSTRAINT venta_ibfk_1 FOREIGN KEY (ID_Cliente) REFERENCES cliente (ID_Cliente),
  CONSTRAINT venta_ibfk_2 FOREIGN KEY (ID_Empleado) REFERENCES empleado (ID_Empleado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DETALLEVENTA (CON FECHA Y HORA)
CREATE TABLE detalleventa (
  ID_Detalle INT AUTO_INCREMENT,
  ID_Venta VARCHAR(15) NOT NULL,
  ISBN VARCHAR(13) NOT NULL,
  Cantidad INT(5) NOT NULL,
  Fecha DATE NOT NULL,
  Hora TIME NOT NULL,
  Total INT(5) NOT NULL,
  PRIMARY KEY (ID_Detalle),
  KEY (ID_Venta),
  KEY (ISBN),
  CONSTRAINT detalleventa_ibfk_1 FOREIGN KEY (ID_Venta) REFERENCES venta (ID_Venta),
  CONSTRAINT detalleventa_ibfk_2 FOREIGN KEY (ISBN) REFERENCES libro (ISBN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
